=== ryales/ryales.github.io/hakluyt/xml/hakluyt_schema.xsd
<?xml version="1.0"?>

<!-- AUTHOR: RACHEL YALES                        -->
<!-- MASTERS DISSERTATION 2015                   -->
<!-- SUPERVISOR: OLIVER DUKE-WILLIAMS            -->
<!-- SCHEMA FOR HAKLUYT AMERICAN VOYAGE ACCOUNTS -->

  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- ROOT ELEMENT -->
    <xs:element name="extracts">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="extract" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="title">
                  <xs:complexType mixed="true">
                    <xs:choice maxOccurs="unbounded" minOccurs="0">
                      <xs:element ref="place"/>
                      <xs:element ref="person"/>
                      <xs:element ref="ship"/>
                    </xs:choice>
                  </xs:complexType>
                </xs:element>
                <xs:element ref="para"/>
              </xs:sequence>
              <xs:attribute name="id" type="xs:string" use="required"/>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:complexType>
    </xs:element>

    <!-- GLOBAL ELEMENTS -->
    <xs:element name="para">
      <xs:complexType mixed="true">
        <xs:sequence>
          <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element ref="person"/>
            <xs:element ref="place"/>
            <xs:element ref="date"/>
            <xs:element ref="ship"/>
            <!-- IGNORED WHEN TEXT IS OUTPUT -->
            <xs:element name="sidenote" type="xs:string"/>
            <xs:element name="note" type="xs:string"/>
          </xs:choice>
        </xs:sequence>
      </xs:complexType>
    </xs:element>
    <xs:element name="person" type="xs:string"/>
    <!-- FOR THE FUTURE WHEN XML DOM GETS WORKED OUT -->
        <!-- <xs:complexType  mixed="true"> -->
        <!-- <xs:attribute name="personID" type="xs:string" use="required" /> -->
        <!-- </xs:complexType> --> 
    <xs:element name="date">  
      <xs:complexType  mixed="true">
        <xs:attribute name="date" type="xs:date"/>
      </xs:complexType>
    </xs:element>
    <xs:element name="place" type="xs:string"/>  
      <!-- FOR THE FUTURE WHEN XML DOM GETS WORKED OUT -->
        <!-- <xs:complexType  mixed="true"> -->
          <!-- <xs:attribute name="lat" type="xs:float"/> -->
          <!-- <xs:attribute name="long" type="xs:float"/> -->
          <!-- <xs:attribute name="placeID" type="xs:string" use="required" /> -->
        <!-- </xs:complexType> -->
    <xs:element name="ship" type="xs:string"/>
  </xs:schema>

=== ryales/ryales.github.io/hakluyt/xml/frobisher.xml
<?xml version="1.0"?>

<extracts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hakluyt_schema.xsd">
  <extract id="E001">
    <title>
      The first Voyage of <person>M. Martine Frobisher</person>, to the Northwest, for the search of the straight or passage to <place>China</place>, written by <person>Christopher Hall</person>, Master in the <ship>Gabriel</ship>, and made in the yeere of our Lord 1576.
    </title>

    <para>
      <date date="1576-06-07">The 7. of Iune being Thursday</date>, the two Barks, viz. the <ship>Gabriel</ship>, and the
      <ship>Michael</ship> <note>M. Matthew Kinderslye was Captaine of the Michael.</note>
      and our Pinnesse set saile at <place>Ratcliffe</place>, and bare down to <place>Detford</place>, and
      there we ancred: the cause was that our Pinnesse burst her boulsprit, and
      foremast aboard of a ship that rode at <place>Detford</place>, else wee meant to haue past
      that day by the Court then at <place>Grenewich</place>.
    </para>

    <para>
      The <date date="1576-06-08">8. day being Friday</date>, about 12 of the clocke we wayed at <place>Detford</place>, and
      set saile all three of vs, and bare downe by the Court, where we shotte off
      our ordinance and made the best shew we could: <person>Her Maiestie</person> beholding the
      same, commended it, and bade vs farewell, with shaking her hand at vs out
      of the window. Afterward shee sent <person>a Gentleman</person> aboord of vs, who declared
      that <person>her Maiestie</person> had good liking of our doings, and thanked vs for it, and
      also willed <person>our Captaine</person> to come the next day to the Court to take his
      leaue of her.
    </para>

    <para>
      <date date="1576-06-08">The same day</date> towards night <person>M. Secretarie Woolly</person> came aboorde of vs, and
      declared to the company, that <person>her Maiestie</person> had appointed him to giue them
      charge to be obedient, and diligent to <person>their Captaine</person>, and gouernours in
      all things, and wished vs happie successe.
    </para>

    <para>
      The <date date="1576-06-12">12. day</date> being ouer against <place>Grauesend</place>, by the castle or blockehouse, we
      obserued the latitude, which was 51. degrees 33. min. And in that place the
      variation of the Compasse is 11. degrees and a halfe.
    </para>

    <para>
      <sidenote>Faire Island.</sidenote> The <date date="1576-06-24">24. day</date> at 2. of the clocke after noone, I
      had sight of <place>Faire yle</place>, being from vs 6. leagues North and by East, and
      when I brought it Northwest and by North, it did rise at the Southermost
      ende with a litle hommocke, and swampe in the middes.
    </para>

    <para>
      <sidenote>Shotland.</sidenote> The <date date="1576-06-25">25. day</date> from 4. to 8. a clocke in the forenoone,
      the winde at Northwest and by North a fresh gale, I cast about to the
      Westward, <place>the Southermost head of Shotland called Swinborne head</place>
      Northnorthwest from me, and the land of <place>Faire yle</place>, West Southwest from me.
      I sailed directly to the North head of that said land, sounding as I ranne
      in, hauing 60. 50. and 40. fathoms, and gray redde shels: and within halfe
      a mile of that Island, there are 36. fathoms, for I sailed to that Island
      to see whether there were any roadesteede for a Northwest winde, and I
      found by my sounding hard rockes, and foule ground, and deepe water, within
      two cables length of the shoare, 28. fathome, and so did not ancre but
      plied to and fro with my foresaile, and mizen till it was a high water
      vnder the Island. The tide setteth there Northwest and Southeast: the flood
      setteth Southeast, and the ebbe Northwest.
    </para>

    <para>
      The <date date="1576-06-26">26. day</date> hauing the winde at South a faire gale, sayling from <place>Faire yle</place>
      to <place>Swinborne head</place>, I did obserue the latitude, the <place>Island of Fowlay</place> being
      West Northwest from me 6. leagues, and <place>Swinborne head</place> East southeast from
      me, I found my eleuation <note>By eleuation he meaneth the
      distance of the sunne from the zenith.</note> to be 37. degr and my declination
      22. degr. 46 min. So that my latitude was 59. degr. 46. min. <sidenote>S.
      Tronions.</sidenote> At that present being neere to <place>Swinborne head</place>, hauing a leake
      which did trouble vs, as also to take in fresh water, I plyed roome with a
      sound, which is called <place>S. Tronions</place>, and there did ancre in seuen fathoms
      water, and faire sande. You haue comming in the sounds mouth in the entring
      17. 15. 12. 10. 9. 8. and 7. fathoms, and the sound lyeth in North
      northwest, and there we roade to a West sunne, and stopped our leake, and
      hauing refreshed our selues with water, at a North northwest sunne, I set
      saile from <place>S. Tronions</place> the winde at South Southest, and turned out till wee
      were cleare of the sound, and so sailed West to go cleare of the <place>Island of
      Fowlay</place>. <sidenote>Fowlay Island.</sidenote> And running off toward <place>Fowlay</place>, I
      sounded, hauing fiftie fathome, and streamie ground, and also I sounded
      <place>Fowlay</place> being North from mee one league off that Islande, hauing fiftie
      fathome at the South head, and streamie ground, like broken otmell, and one
      shell being redde and white like mackerell.
    </para>

    <para>
      <sidenote>Latitude 59. deg. 59. min. Here they begin to saile West and by
      North.</sidenote> The <date date="1576-06-27">27. day</date> at a South sunne I did obserue the latitude, the <place>Island
      of Fowlay</place> being from me two leagues East Northeast: I found my selfe to be
      in latitude 59. degrees, 59. min truly obserued, the winde at South
      Southwest: I sailed West and by North.
    </para>

    <para>
      From 12. to foure a clocke afternoone, the wind at South, a faire gale the
      shippe sailed West and by North 6. leagues, and at the ende of this watch,
      I sounded hauing 60. fathome, with little stones and shels, <place>the Island</place> from
      vs 8. leagues East.
    </para>

    <para>
      <sidenote>July the first.</sidenote> The <date date="1576-07-01">first of Iuly</date>, from 4. to 8. a clocke, wee
      sailed West 4. glasses 4. leagues, and at that present we had so much winde
      that we spooned afore the sea Southwest 2. leagues.
    </para>

    <para>
      The 3. day we found our Compasse to bee varied one point to Westwards: this
      day from 4. to 8. a clocke we sailed West and by North 6 leagues.
    </para>

    <para>
      From 8. to 12. a clocke at noone West and by North 4. leagues.
      <sidenote>The Compasse varying Westwards one point.</sidenote> At that present I found our
      compasse to be varied 11 deg. and one 4. part to the Westwards, which is
      one point.
    </para>

    <para>
      <sidenote>The Island of Friseland.</sidenote> The <date date="1576-07-11">11. day</date> at a Southeast sunne we
      had sight of <place>the land of Friseland</place> bearing from vs West northwest 16.
      leagues, and rising like pinacles of steeples, and all couered with snowe.
      I found my selfe in 61. degr. of latitude. Wee sailed to the shoare and
      could finde no ground at 150. fathoms, we hoised out our boate, and the
      Captaine with 4. men rowed to the shoare to get on land, but the land lying
      full of yce, they could not get on land, and so they came aboord againe: We
      had much adoe to get cleare of the yce by reason of the fogge. Yet from
      Thursday 8. a clocke in the morning to Friday at noone we sailed Southwest
      20. leagues.
    </para>

    <para>
      The <date date="1576-07-18">18. day</date> at a Southwest sunne I found the sunne to be eleuated 33. deg.
      And at a Southsoutheast sunne 40. deg. So I obserued it till I found it at
      the highest, and then it was eleuated 52. deg. <sidenote>The variation of
      the needle two points and a halfe to the West.</sidenote> I iudged the variation of
      the Compasse to be 2. points and a halfe to the Westward.
    </para>

    <para>
      <sidenote>A great drift of yce.</sidenote> The <date date="1576-07-21">21. day</date> we had sight of a great drift
      of yce, seeming <place>a firme land</place>, and we cast Westward to be cleare of it.
    </para>

    <para>
      <sidenote>The latitude of 62. degrees 2. min.</sidenote> The 26. we had sight of a
      land of yce: the latitude was 62. degrees, and two minutes.
    </para>

    <para>
      <sidenote>Sight of land supposed to haue been Labrador.</sidenote> The <date date="1576-07-28">28. day</date> in
      the morning was very foggie: but at the clearing vp of the fogge, we had
      sight of lande, which I supposed to be <place>Labrador</place>, with great store of yce
      about the land: I ranne in towards it, and sownded, but could get no ground
      at 100. fathom, and the yce being so thicke, I could not get to the shoare,
      and so lay off, and came cleare of the yce. Upon Munday we came within a
      mile of the shoare, and sought a harborowe: all the sownd was full of yce,
      and our boate rowing a shoare, could get no ground at 100. fathom, within a
      Cables length of the shoare: then we sailed Eastnortheast along the shoare,
      for so the lande lyeth, and the currant is there great, setting Northeast,
      and Southwest: and if we could haue gotten anker ground, wee would haue
      seene with what force it had runne, but I iudge a ship may driue a league
      and a halfe, in one houre, with that tide.
    </para>

    <para>
